name: Create Event Example
on :
    workflow_dispatch:

jobs:
    createevent_demo:
        runs-on: ubuntu-latest
        steps:
            - name: Create Event Example
              run: echo "This is an example of a create event triggered by a tag starting with 'eventtag'"
            - name: Print Tag Name
              run: echo "Tag Name:${{ github.ref_name }}"
            - name: Print Repository Name
              run: |
                echo "Repository Name:${{ github.repository }}"
                echo "WorkFlow NAme:${{github.action}}"
                echo "Path: ${{github.ref}}"  
