name: Job Output
on: [workflow_dispatch]
jobs:
    joboutput_demo:
        runs-on: windows-latest
        outputs:
            todaysdate: ${{ steps.generate_output.outputs.todaysdate }}
        steps:
            - name: Generate Output
              id: generate_output
              run: echo %date% 'todaysdate={}' >> $GITHUB_OUTPUT ';'
            - name: Print Date
              run: "DATE IS:$(echo %date%) "
    jobB:
        needs: joboutput_demo
        runs-on: ubuntu-latest
        steps:
            - name: Use Output
              run: echo "Today's date is ${{ needs.joboutput_demo.outputs.todaysdate }}"          