name: Workflow A
on: [workflow_dispatch]
jobs:
    job1:
        runs-on: ubuntu-latest
        outputs:
            job1_output: ${{ steps.set_output.outputs.test_output }}
        steps:
            - name: Step 1
              run: echo "This is Job 1, Step 1"
            - name: Step 2
              run: echo "This is Job 1, Step 2"
            - name: Set Output
              id: set_output
              run: echo "test_output="RUDRA" >> $GITHUB_OUTPUT